import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { oriaColorFamilies, oriaColorSteps, oriaColors, toOriaColorVariable } from "../dist/index.js";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const declarations = oriaColorFamilies.flatMap(family => oriaColorSteps.map(step => `  ${toOriaColorVariable(family, step)}: ${oriaColors[family][step]};`));
declarations.push(`  --oria-palette-black: ${oriaColors.black};`, `  --oria-palette-white: ${oriaColors.white};`, `  --oria-palette-inherit: ${oriaColors.inherit};`, `  --oria-palette-transparent: ${oriaColors.transparent};`, `  --oria-palette-current: ${oriaColors.current};`);

const mappings = oriaColorFamilies.flatMap(family => oriaColorSteps.map(step => `  --color-${family}-${step}: var(${toOriaColorVariable(family, step)});`));
mappings.push("  --color-black: var(--oria-palette-black);", "  --color-white: var(--oria-palette-white);", "  --color-inherit: var(--oria-palette-inherit);", "  --color-transparent: var(--oria-palette-transparent);", "  --color-current: var(--oria-palette-current);");

await mkdir(resolve(packageRoot, "dist"), { recursive: true });
await writeFile(resolve(packageRoot, "dist/colors.css"), `/* Generated by @oriatheme/colors. */\n:root {\n${declarations.join("\n")}\n}\n`);
await writeFile(resolve(packageRoot, "dist/tailwind.css"), `/* Tailwind CSS v4 color bridge. */\n@theme inline {\n${mappings.join("\n")}\n}\n`);
