<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue";
import type { ResolvedMode, ThemeDefinition } from "@oriatheme/core";
import type { ThemeEditorSession, ThemeEditorSnapshot } from "@oriatheme/editor-core";
import type { OriaThemeRuntime, ThemeSnapshot } from "@oriatheme/runtime-dom";
import ConfirmationDialog from "./overlays/ConfirmationDialog.vue";
import ThemeAccordion from "./ThemeAccordion.vue";
import ThemeListItem from "./ThemeListItem.vue";
type ThemeAction = "apply" | "edit" | "copy" | "delete";
interface PendingAction { readonly action: ThemeAction; readonly themeId: string; readonly origin?: { readonly x: number; readonly y: number } }
const props = defineProps<{ runtime?: OriaThemeRuntime; mode: ResolvedMode; snapshot: ThemeEditorSnapshot; session: ThemeEditorSession }>();
const emit = defineEmits<{ edit: [] }>();
const runtimeSnapshot = ref<ThemeSnapshot>(); const pending = ref<PendingAction>(); const error = ref(""); let unsubscribe = (): void => {};
watch(() => props.runtime, runtime => { unsubscribe(); if (!runtime) { runtimeSnapshot.value = undefined; return; } runtimeSnapshot.value = runtime.getSnapshot(); unsubscribe = runtime.subscribe(() => { runtimeSnapshot.value = runtime.getSnapshot(); }); }, { immediate: true });
onBeforeUnmount(() => unsubscribe());
const customThemes = computed(() => [...(runtimeSnapshot.value?.customThemes ?? [])].sort((left,right) => (right.updatedAt ?? right.createdAt ?? 0) - (left.updatedAt ?? left.createdAt ?? 0)));
const allThemes = computed(() => [...(runtimeSnapshot.value?.presets ?? []), ...(runtimeSnapshot.value?.customThemes ?? [])]);
const center = (element: HTMLElement): { x: number; y: number } => { const rect = element.getBoundingClientRect(); return { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 }; };
const copyIdentity = (theme: ThemeDefinition): { id: string; name: string } => { const occupied = new Set(allThemes.value.map(item => item.id)); let number = 1; let id = ""; while (!id || occupied.has(id)) { const suffix = number === 1 ? "-copy" : `-copy-${number}`; id = `${theme.id.slice(0,64-suffix.length).replace(/-+$/u,"") || "theme"}${suffix}`; number += 1; } return { id, name: `${theme.name} Copy${number > 2 ? ` ${number - 1}` : ""}`.slice(0,120) }; };
const perform = (action: ThemeAction, theme: ThemeDefinition, origin?: { x: number; y: number }): void => { if (!props.runtime) return; error.value = ""; try { if (action === "apply") props.runtime.setTheme(theme.id,{ animate: true, ...(origin ? { origin } : {}) }); else if (action === "edit") { if (props.snapshot.draft.id !== theme.id) props.session.reload(theme); emit("edit"); } else if (action === "copy") { props.session.reload(props.runtime.duplicateTheme(theme.id,copyIdentity(theme))); emit("edit"); } else props.runtime.removeCustomTheme(theme.id); } catch (cause) { error.value = cause instanceof Error ? cause.message : "The theme action could not be completed."; } };
const request = (action: ThemeAction, theme: ThemeDefinition, element: HTMLElement): void => { const active = runtimeSnapshot.value?.preference.activeThemeId; const discards = action === "copy" || (action === "edit" && props.snapshot.draft.id !== theme.id) || (action === "apply" && active !== theme.id); const origin = center(element); if (action === "delete" || (props.snapshot.dirty && discards)) pending.value = { action, themeId: theme.id, origin }; else perform(action,theme,origin); };
const rename = (theme: ThemeDefinition, name: string): void => { if (!props.runtime) return; try { if (props.snapshot.draft.id === theme.id) props.session.setName(name); else props.runtime.updateCustomTheme(theme.id,{ name }); } catch (cause) { error.value = cause instanceof Error ? cause.message : "The theme could not be renamed."; } };
const pendingTheme = computed(() => pending.value ? allThemes.value.find(theme => theme.id === pending.value?.themeId) : undefined);
const deleting = computed(() => pending.value?.action === "delete");
const confirm = (): void => { if (pending.value && pendingTheme.value) perform(pending.value.action,pendingTheme.value,pending.value.origin); pending.value = undefined; };
</script>
<template><main v-if="runtime && runtimeSnapshot" data-oria-editor-workspace data-oria-editor-themes role="tabpanel" aria-labelledby="oria-tab-themes"><p v-if="error" data-oria-editor-theme-error role="alert">{{ error }}</p><ThemeAccordion title="My themes" :count="customThemes.length" empty="Custom themes you save or copy will appear here."><ThemeListItem v-for="theme in customThemes" :key="theme.id" :theme="theme" :mode="mode" :active="runtimeSnapshot.preference.activeThemeId === theme.id" :display-name="snapshot.draft.id === theme.id ? snapshot.draft.name : theme.name" editable @apply="origin => request('apply',theme,origin)" @edit="origin => request('edit',theme,origin)" @copy="origin => request('copy',theme,origin)" @delete="origin => request('delete',theme,origin)" @rename="name => rename(theme,name)" /></ThemeAccordion><ThemeAccordion title="Presets" :count="runtimeSnapshot.presets.length" empty="No preset themes are available."><ThemeListItem v-for="theme in runtimeSnapshot.presets" :key="theme.id" :theme="theme" :mode="mode" :active="runtimeSnapshot.preference.activeThemeId === theme.id" @apply="origin => request('apply',theme,origin)" @copy="origin => request('copy',theme,origin)" /></ThemeAccordion><ConfirmationDialog :open="pendingTheme !== undefined" :title="deleting ? `Delete ${pendingTheme?.name ?? 'theme'}?` : `${pending?.action === 'copy' ? 'Copy' : pending?.action === 'edit' ? 'Edit' : 'Apply'} ${pendingTheme?.name ?? 'theme'}?`" :description="deleting ? 'This custom theme will be permanently removed. If it is active, OriaTheme will return to the default theme.' : 'Continuing will discard the unsaved edits in the current draft.'" :confirm-label="deleting ? 'Delete theme' : 'Discard and continue'" :destructive="deleting" @confirm="confirm" @cancel="pending = undefined" /></main><main v-else data-oria-editor-workspace role="tabpanel" aria-labelledby="oria-tab-themes"><p data-oria-editor-empty>Theme management requires a runtime.</p></main></template>
