import type { ReactNode } from "react";
import { CodeBlock } from "@/components/docs/code-block";
import { PackageManagerTabs } from "@/components/docs/package-manager-tabs";
import type { Locale } from "@/lib/i18n";

export const apiPackages = ["core", "runtime-dom", "react", "vue", "colors", "presets", "editor-core", "react-editor", "vue-editor", "cli"] as const;
export type ApiPackageSlug = (typeof apiPackages)[number];

type ApiPage = { title: string; eyebrow: string; description: string; toc: { id: string; label: string }[]; body: ReactNode };
type ExportItem = { name: string; signature: string; description: string };

function ExportsTable({ items }: { readonly items: readonly ExportItem[] }) {
  return <div className="docs-table-wrap"><table><thead><tr><th>Export</th><th>Signature</th><th>Description</th></tr></thead><tbody>{items.map(item => <tr key={item.name}><td><code>{item.name}</code></td><td><code>{item.signature}</code></td><td>{item.description}</td></tr>)}</tbody></table></div>;
}

function PackageIntro({ name, install, environment, zh }: { readonly name?: string; readonly install: string; readonly environment: ReactNode; readonly zh: boolean }) {
  return <section id="package" data-package={name}><h2>{zh ? "包与运行环境" : "Package and environment"}</h2><p>{environment}</p><PackageManagerTabs label={zh ? "选择包管理器" : "Choose a package manager"} commands={{ pnpm: `pnpm add ${install}`, npm: `npm install ${install}`, yarn: `yarn add ${install}`, bun: `bun add ${install}` }} /><p>{zh ? "选择使用方项目已有的一种包管理器和 lockfile；示例只使用 package root export，不要从 src、dist 或 registry template 深层导入。" : "Use the package manager and lockfile already chosen by the consumer project. Examples use package-root exports only; do not deep-import from src, dist, or registry templates."}</p></section>;
}

const coreExports: readonly ExportItem[] = [
  { name: "defineTokenContract", signature: "(input: TokenContractInput) => TokenContract", description: "Creates an immutable, validated contract." },
  { name: "extendTokenContract", signature: "(base, extension) => TokenContract", description: "Adds contract tokens without losing the base." },
  { name: "getTokenDefinition", signature: "(contract, path) => TokenDefinition | undefined", description: "Looks up a declared token." },
  { name: "token / colorToken", signature: "(type, options) => TokenDefinition", description: "Creates contract-token definitions." },
  { name: "validateTheme", signature: "(input, contract) => ValidationResult<ThemeDefinition>", description: "Never throws for untrusted serialized input." },
  { name: "normalizeTheme", signature: "(theme, contract) => ThemeDefinition", description: "Canonicalizes order and fills contract defaults." },
  { name: "resolveTheme", signature: "(theme, mode, options?) => ResolvedTheme", description: "Resolves references and compiles safe CSS variables." },
  { name: "resolveThemeWithContract", signature: "(theme, contract, mode, options?) => ResolvedTheme", description: "Safe resolver with an explicit contract." },
  { name: "cloneTheme", signature: "(theme, identity, clock?) => ThemeDefinition", description: "Makes a timestamped complete copy." },
  { name: "createThemeFromSeed", signature: "(seed, options) => ThemeDefinition", description: "Creates a complete standard-contract custom theme." },
  { name: "exportTheme", signature: "(theme) => string", description: "Serializes the public theme format." },
  { name: "importTheme", signature: "(json, options) => ImportResult", description: "Validates JSON, forces custom kind, and handles conflicts." },
  { name: "analyzeTheme", signature: "(theme, contract) => ThemeDiagnostics", description: "Returns blocking errors and contrast warnings." },
  { name: "contrastRatio", signature: "(foreground, background) => number", description: "Computes WCAG contrast for static hex colors." },
  { name: "toCssVariable", signature: "(path, prefix?) => `--${string}`", description: "Converts a validated path to a CSS custom property." },
  { name: "isTokenPath", signature: "(value) => value is TokenPath", description: "Narrows a string to a branded token path." },
];

const runtimeMethods: readonly ExportItem[] = [
  { name: "start / destroy", signature: "() => void", description: "Attach or release browser listeners and DOM ownership." },
  { name: "getSnapshot / subscribe", signature: "() => ThemeSnapshot / (listener) => unsubscribe", description: "Read or subscribe to the external store." },
  { name: "setTheme / setAppearance", signature: "(id | mode, options?) => void", description: "Select an existing theme or user preference; can animate explicit actions." },
  { name: "createCustomTheme", signature: "({ theme }) => ThemeDefinition", description: "Persists a complete valid custom theme." },
  { name: "updateCustomTheme", signature: "(id, patch, options?) => ThemeDefinition", description: "Updates an existing custom theme only." },
  { name: "duplicateTheme / removeCustomTheme", signature: "(id, identity) => ThemeDefinition / (id) => void", description: "Copies a preset/custom theme or removes a custom theme." },
  { name: "previewTheme", signature: "(theme, mode?) => PreviewHandle", description: "Applies a valid in-memory preview; dispose restores formal state." },
  { name: "exportTheme / importTheme", signature: "(id) => string / (json, options?) => ThemeDefinition", description: "Exports a saved theme or imports a fully validated custom theme." },
  { name: "reset", signature: "() => void", description: "Returns runtime preference and custom state to its initial configuration." },
];

function sharedTypes(zh: boolean, names: string) { return <section id="types"><h2>{zh ? "重要类型与边界" : "Important types and boundaries"}</h2><p>{names}</p></section>; }

export function getApiPage(locale: Locale, slug: ApiPackageSlug): ApiPage {
  const zh = locale === "zh";
  if (slug === "core") return {
    eyebrow: zh ? "API 参考 · 核心主题" : "API reference · Core themes", title: "@oriatheme/core", description: zh ? "无 DOM、Storage、React 或 Vue 依赖的 Theme Contract、校验、解析和导入导出 API。" : "Theme-contract, validation, resolution, and import/export APIs with no DOM, Storage, React, or Vue dependency.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "functions", label: zh ? "函数" : "Functions" }, { id: "types", label: zh ? "类型" : "Types" }],
    body: <><PackageIntro install="@oriatheme/core" zh={zh} environment={zh ? "纯 TypeScript；可在 Node、SSR 和浏览器模块求值中使用。" : "Pure TypeScript; safe in Node, SSR, and browser module evaluation."} /><section id="functions"><h2>{zh ? "公开函数" : "Public functions"}</h2><ExportsTable items={coreExports} /><CodeBlock language="ts">{`import { oriaStandardContract, resolveTheme, validateTheme } from "@oriatheme/core";\n\nconst checked = validateTheme(input, oriaStandardContract);\nif (checked.ok) {\n  const resolved = resolveTheme(checked.value, "dark");\n  // resolved.variables is safe compiler output.\n}`}</CodeBlock><p>{zh ? "对用户输入优先使用 validateTheme 或 importTheme 的结果分支；不要匹配错误文本。" : "Branch on validateTheme or importTheme results for user input; do not match error messages."}</p></section>{sharedTypes(zh, zh ? "ThemeDefinition 是 v1 完整序列化主题；TokenContract 描述路径和安全值类型；ValidationResult / ImportResult 以 ok 判别；OriaThemeError 的 code 是稳定错误分支。ResolvedTheme 包含已编译的变量和 colorScheme。" : "ThemeDefinition is the complete v1 serialized theme; TokenContract describes paths and safe values; ValidationResult / ImportResult discriminate on ok; OriaThemeError.code is the stable error branch. ResolvedTheme contains compiled variables and colorScheme.")}</>,
  };
  if (slug === "runtime-dom") return {
    eyebrow: zh ? "API 参考 · 浏览器 Runtime" : "API reference · Browser runtime", title: "@oriatheme/runtime-dom", description: zh ? "浏览器端外部 store、原子 DOM 应用、持久化、Bootstrap 与 View Transition。" : "Browser external store, atomic DOM application, persistence, Bootstrap, and View Transition.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "factory", label: zh ? "工厂与 Bootstrap" : "Factory and Bootstrap" }, { id: "runtime", label: "OriaThemeRuntime" }, { id: "types", label: zh ? "类型" : "Types" }],
    body: <><PackageIntro name="runtime-dom" install="@oriatheme/presets @oriatheme/runtime-dom" zh={zh} environment={zh ? "SSR 导入安全；start、Storage 和 DOM 写入只在浏览器执行。" : "SSR-safe to import; start, Storage, and DOM writes run only in the browser."} /><section id="factory"><h2>{zh ? "工厂与首屏 API" : "Factory and first-paint APIs"}</h2><ExportsTable items={[{ name: "createOriaThemeRuntime", signature: "(config: OriaThemeConfig) => OriaThemeRuntime", description: "Creates the SSR-safe store and client DOM runtime." }, { name: "bootstrapTheme", signature: "(options?: BootstrapOptions) => void", description: "Applies one valid active snapshot before framework mount." }, { name: "createBootstrapScript", signature: "(options: BootstrapOptions) => string", description: "Creates a self-contained script for a caller-supplied snapshot." }, { name: "createBootstrapStorageScript", signature: "(options?) => string", description: "Creates a head-safe LocalStorage bootstrap script." }]} /><CodeBlock language="ts">{`import { bootstrapTheme, createOriaThemeRuntime } from "@oriatheme/runtime-dom";\nimport { oriaPresetThemes } from "@oriatheme/presets";\n\nbootstrapTheme();\nconst runtime = createOriaThemeRuntime({\n  presets: oriaPresetThemes,\n  defaultThemeId: "oria-default",\n});\nruntime.start();`}</CodeBlock></section><section id="runtime"><h2>OriaThemeRuntime</h2><ExportsTable items={runtimeMethods} /></section>{sharedTypes(zh, zh ? "OriaThemeConfig 要求 presets 和 defaultThemeId；ThemeSnapshot 提供 preference、resolvedMode、resolvedTheme、preset/custom 列表和 error。ThemeStorage 可替换默认持久化，ThemeChangeOptions 的 animate 只用于显式用户操作。persist appearance，绝不持久化 resolvedMode。" : "OriaThemeConfig requires presets and defaultThemeId; ThemeSnapshot exposes preference, resolvedMode, resolvedTheme, preset/custom lists, and error. ThemeStorage can replace default persistence, and ThemeChangeOptions.animate is for explicit user actions only. Persist appearance, never resolvedMode.")}</>,
  };
  if (slug === "react") return {
    eyebrow: zh ? "API 参考 · React" : "API reference · React", title: "@oriatheme/react", description: zh ? "将同一个 Runtime 外部 store 接入 React 的 Provider 与 Hooks；不包含第二套状态机。" : "Connect one runtime external store to React with a Provider and Hooks; no second state machine.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "Exports" }, { id: "types", label: zh ? "边界" : "Boundaries" }],
    body: <><PackageIntro name="react" install="@oriatheme/presets @oriatheme/runtime-dom @oriatheme/react" zh={zh} environment={zh ? "React 18.2 或 19 的浏览器 Provider；模块本身可 SSR 导入。" : "Browser Provider for React 18.2 or 19; the module itself is SSR-safe to import."} /><section id="exports"><h2>Exports</h2><ExportsTable items={[{ name: "OriaThemeProvider", signature: "({ config, runtime?, children }: OriaThemeProviderProps) => ReactElement", description: "Starts an owned runtime or uses the supplied runtime for descendants." }, { name: "useOriaTheme", signature: "() => { snapshot, runtime, setTheme, setAppearance }", description: "Reads the full immutable runtime snapshot and bound actions." }, { name: "useThemeSnapshot", signature: "<T>(selector, isEqual?) => T", description: "Selects a snapshot slice while preserving equal references." }]} /><CodeBlock language="tsx">{`import { OriaThemeProvider, useOriaTheme } from "@oriatheme/react";\n\nfunction Controls() {\n  const { setAppearance, setTheme } = useOriaTheme();\n  return <button onClick={() => setTheme("oria-ocean")}>Ocean</button>;\n}`}</CodeBlock></section>{sharedTypes(zh, zh ? "OriaThemeProviderProps 接受 OriaThemeConfig 或外部 OriaThemeRuntime。Provider 只应在客户端挂载；在 Next 首屏先输出已验证的默认变量和 Bootstrap script。" : "OriaThemeProviderProps accepts an OriaThemeConfig or external OriaThemeRuntime. Mount the Provider only on the client; for Next first paint, output validated default variables and a Bootstrap script first.")}</>,
  };
  if (slug === "vue") return {
    eyebrow: zh ? "API 参考 · Vue" : "API reference · Vue", title: "@oriatheme/vue", description: zh ? "将同一个 Runtime 接入 Vue Plugin、provide 与 Composable；不复制 Runtime 状态。" : "Connect one runtime to a Vue Plugin, provide, and Composable without mirroring runtime state.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "Exports" }, { id: "types", label: zh ? "边界" : "Boundaries" }],
    body: <><PackageIntro name="vue" install="@oriatheme/presets @oriatheme/runtime-dom @oriatheme/vue" zh={zh} environment={zh ? "Vue 3.5 的浏览器 Plugin/provide；模块本身可 SSR 导入。" : "Browser Plugin/provide for Vue 3.5; the module itself is SSR-safe to import."} /><section id="exports"><h2>Exports</h2><ExportsTable items={[{ name: "createOriaTheme", signature: "(config: OriaThemeConfig) => Plugin", description: "Creates a plugin that owns the runtime it constructs." }, { name: "provideOriaTheme", signature: "(config | runtime) => OriaThemeRuntime", description: "Provides an owned or caller-supplied runtime in the current tree." }, { name: "useOriaTheme", signature: "() => { snapshot, runtime, setTheme, setAppearance }", description: "Returns the runtime and a readonly shallow snapshot ref." }]} /><CodeBlock language="vue">{`<script setup lang="ts">\nimport { useOriaTheme } from "@oriatheme/vue";\nconst { snapshot, setAppearance } = useOriaTheme();\n</script>\n<template><button @click="setAppearance('system')">{{ snapshot.resolvedMode }}</button></template>`}</CodeBlock></section>{sharedTypes(zh, zh ? "snapshot 是 DeepReadonly<ShallowRef<ThemeSnapshot>>。不要在 Pinia 或其他 store 里复制主题、appearance 或 resolvedMode。" : "snapshot is a DeepReadonly<ShallowRef<ThemeSnapshot>>. Do not mirror theme, appearance, or resolvedMode into Pinia or another store.")}</>,
  };
  if (slug === "colors") return {
    eyebrow: zh ? "API 参考 · 基础色" : "API reference · Base colors", title: "@oriatheme/colors", description: zh ? "不随主题切换的稳定基础色库，以及 Tailwind v4 兼容的公开 CSS 子路径。" : "Stable base colors that do not change with a theme, plus Tailwind v4-compatible public CSS subpaths.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "Exports" }, { id: "css", label: "CSS" }],
    body: <><PackageIntro name="colors" install="@oriatheme/colors" zh={zh} environment={zh ? "静态值；可在任意 JavaScript、CSS 与 SSR 环境使用。" : "Static values; usable from JavaScript, CSS, and SSR environments."} /><section id="exports"><h2>Exports</h2><ExportsTable items={[{ name: "oriaColors", signature: "OriaColors", description: "26 immutable named scales plus black, white, inherit, transparent, and current." }, { name: "oriaColorFamilies", signature: "readonly OriaColorFamily[]", description: "The 26 stable family names." }, { name: "oriaColorSteps", signature: "readonly OriaColorStep[]", description: "50 through 950 in eleven steps." }, { name: "toOriaColorVariable", signature: "(family, step) => `--oria-palette-${family}-${step}`", description: "Returns a stable base-color custom property name." }]} /><CodeBlock language="ts">{`import { oriaColors, toOriaColorVariable } from "@oriatheme/colors";\n\nconst blue = oriaColors.blue[500];\nconst variable = toOriaColorVariable("blue", 500);`}</CodeBlock></section><section id="css"><h2>CSS</h2><CodeBlock language="css">{`@import "@oriatheme/colors/styles.css";\n@import "tailwindcss";\n@import "@oriatheme/colors/tailwind.css";`}</CodeBlock><p>{zh ? "基础色不会随 OriaTheme 切换。需要随主题变化的界面值应使用 Runtime 写入的语义 --oria-* 变量。" : "Base colors never change with OriaTheme. Use semantic --oria-* variables written by the runtime for theme-responsive UI."}</p></section></>,
  };
  if (slug === "presets") return {
    eyebrow: zh ? "API 参考 · 官方预设" : "API reference · Official presets", title: "@oriatheme/presets", description: zh ? "完整、已经校验的官方 ThemeDefinition 集合与最小分类目录。" : "The complete, validated official ThemeDefinition collection and its minimal category catalog.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "Exports" }, { id: "types", label: zh ? "目录边界" : "Catalog boundary" }],
    body: <><PackageIntro name="presets" install="@oriatheme/presets" zh={zh} environment={zh ? "静态 ThemeDefinition 数据；可在 SSR 和浏览器中使用。" : "Static ThemeDefinition data; usable in SSR and browsers."} /><section id="exports"><h2>Exports</h2><ExportsTable items={[{ name: "oriaPresetThemes", signature: "readonly ThemeDefinition[]", description: "Complete collection for runtime presets." }, { name: "oriaPresetCatalog", signature: "readonly PresetCatalogEntry[]", description: "Each entry has theme and a PresetCategory." }, { name: "oriaDefaultTheme", signature: "ThemeDefinition", description: "Re-exported from @oriatheme/core." }, { name: "named theme exports", signature: "ThemeDefinition", description: "oriaOceanTheme, oriaForestTheme, oriaAuroraTheme, and every other named official preset." }]} /><CodeBlock language="ts">{`import { oriaPresetThemes, oriaOceanTheme } from "@oriatheme/presets";\n\nconst presets = [...oriaPresetThemes];\nconsole.log(oriaOceanTheme.id);`}</CodeBlock><p>{zh ? "全部 named exports：oriaOceanTheme、oriaForestTheme、oriaAuroraTheme、oriaWarmReadingTheme、oriaMonochromeDeployTheme、oriaPrecisionFlowTheme、oriaManuscriptTheme、oriaElevatedSurfaceTheme、oriaBentoUiTheme、oriaDashboardTheme、oriaEditorialTheme、oriaAiNativeTheme、oriaCommandCenterTheme、oriaSpatialUiTheme、oriaMonoTheme、oriaMinimalismTheme、oriaLineArtTheme、oriaGlassTheme、oriaNeoBrutalismTheme、oriaPunchcardTheme、oriaSketchbookTheme、oriaSoftClayTheme、oriaGoldenBazaarTheme、oriaTheoremTheme、oriaNeumorphismTheme、oriaMemphisTheme、oriaSoftUiTheme、oriaCyberpunkTheme、oriaY2kTheme、oriaRetroTerminalTheme、oriaPaperTheme、oriaCalmTheme、oriaPlayfulTheme、oriaPremiumTheme、oriaOrganicTheme、oriaCottagecoreTheme、oriaNatureTheme、oriaRetroTheme、oriaKawaiiTheme、oriaSunsetTheme。" : "Named exports include oriaOceanTheme, oriaForestTheme, oriaAuroraTheme, oriaWarmReadingTheme, oriaMonochromeDeployTheme, oriaPrecisionFlowTheme, oriaManuscriptTheme, oriaElevatedSurfaceTheme, oriaBentoUiTheme, oriaDashboardTheme, oriaEditorialTheme, oriaAiNativeTheme, oriaCommandCenterTheme, oriaSpatialUiTheme, oriaMonoTheme, oriaMinimalismTheme, oriaLineArtTheme, oriaGlassTheme, oriaNeoBrutalismTheme, oriaPunchcardTheme, oriaSketchbookTheme, oriaSoftClayTheme, oriaGoldenBazaarTheme, oriaTheoremTheme, oriaNeumorphismTheme, oriaMemphisTheme, oriaSoftUiTheme, oriaCyberpunkTheme, oriaY2kTheme, oriaRetroTerminalTheme, oriaPaperTheme, oriaCalmTheme, oriaPlayfulTheme, oriaPremiumTheme, oriaOrganicTheme, oriaCottagecoreTheme, oriaNatureTheme, oriaRetroTheme, oriaKawaiiTheme, and oriaSunsetTheme."}</p></section>{sharedTypes(zh, zh ? "PresetCategory 为 oria、brand-product、design-language、visual-style 或 mood-context。官方 catalog 只由 OriaTheme 发布流程维护；应用预设属于使用方配置，不能冒充或覆盖官方预设。" : "PresetCategory is oria, brand-product, design-language, visual-style, or mood-context. The official catalog is maintained only by OriaTheme releases; application presets belong to consumer configuration and cannot impersonate or override official presets.")}</>,
  };
  if (slug === "editor-core") return {
    eyebrow: zh ? "API 参考 · 编辑领域" : "API reference · Editor domain", title: "@oriatheme/editor-core", description: zh ? "无 DOM、Storage 或框架依赖的草稿、字段元数据、智能阶梯、诊断、预览与提交会话。" : "Draft, field metadata, smart scales, diagnostics, preview, and commit sessions with no DOM, Storage, or framework dependency.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "Exports" }, { id: "session", label: "ThemeEditorSession" }, { id: "types", label: zh ? "类型" : "Types" }],
    body: <><PackageIntro name="editor-core" install="@oriatheme/editor-core" zh={zh} environment={zh ? "纯领域逻辑；只有 preview/save 方法接收由使用方创建的 Runtime。" : "Pure domain logic; only preview/save receive a runtime created by the consumer."} /><section id="exports"><h2>Exports</h2><ExportsTable items={[{ name: "describeTokenContract", signature: "(contract?) => readonly TokenFieldDescriptor[]", description: "Stable contract-order field metadata." }, { name: "describeToken", signature: "(path, contract?) => TokenFieldDescriptor | undefined", description: "Looks up one editor field." }, { name: "getTokenModeScope", signature: "(path) => 'shared' | 'mode'", description: "Returns standard-token editing scope." }, { name: "deriveSmartScale", signature: "(input: SmartScaleInput) => readonly DerivedTokenValue[]", description: "Expands a designer-facing master value." }, { name: "preserveScaleOverrides", signature: "(derived, current, customized) => readonly DerivedTokenValue[]", description: "Retains explicitly customized leaves." }, { name: "createThemeEditorIdentity", signature: "(source, existingThemes) => CloneIdentity", description: "Creates a stable unused identity for preset editing." }, { name: "createThemeEditorSession", signature: "(options) => ThemeEditorSession", description: "Creates the framework-independent draft session." }]} /></section><section id="session"><h2>ThemeEditorSession</h2><ExportsTable items={[{ name: "getSnapshot / subscribe", signature: "() => ThemeEditorSnapshot / (listener) => unsubscribe", description: "Read or observe immutable editor state." }, { name: "setName / setToken / setTokens", signature: "(...) => void", description: "Change the draft by name, one token, or an atomic set." }, { name: "removeToken / resetToken / resetMode / resetAll", signature: "(...) => void", description: "Unset or restore draft values." }, { name: "replaceFromJson / exportJson", signature: "(json) => ImportResult / () => string", description: "Atomically import a draft or serialize it." }, { name: "preview", signature: "(runtime, mode?) => ThemeEditorPreviewResult", description: "Previews only complete valid revisions." }, { name: "save", signature: "(runtime) => ThemeEditorSaveResult", description: "Validates, creates/updates custom themes, or reports conflict." }, { name: "reload / destroy", signature: "(theme) => void / () => void", description: "Adopt an external version or release session resources." }]} /></section>{sharedTypes(zh, zh ? "ThemeEditorOptions 需要 source，编辑 preset 时需要 identity。ThemeEditorSaveResult 的失败原因是 validation 或 conflict；ThemeEditorPreviewResult 的失败返回 issues。不要在 React/Vue 或页面层复制草稿状态机。" : "ThemeEditorOptions requires source and requires identity when editing a preset. ThemeEditorSaveResult fails with validation or conflict; ThemeEditorPreviewResult fails with issues. Do not copy this draft state machine into React, Vue, or a route.")}</>,
  };
  if (slug === "react-editor") return {
    eyebrow: zh ? "API 参考 · React 编辑桥接" : "API reference · React editor bridge", title: "@oriatheme/react-editor", description: zh ? "为本地源码 ThemeEditor 提供 React session Provider、订阅与自动预览协调；不导出可视 UI。" : "React session Provider, subscription, and auto-preview coordination for a local source ThemeEditor; it exports no visible UI.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "Exports" }, { id: "boundary", label: zh ? "可视 UI 边界" : "Visible UI boundary" }],
    body: <><PackageIntro name="react-editor" install="@oriatheme/editor-core @oriatheme/react-editor" zh={zh} environment={zh ? "React 18.2 或 19 的客户端桥接；使用本地 CLI 安装的 ThemeEditor 作为可视根。" : "React 18.2 or 19 client bridge; use a locally CLI-installed ThemeEditor as the visible root."} /><section id="exports"><h2>Exports</h2><ExportsTable items={[{ name: "ThemeEditorProvider", signature: "({ session?, options?, children }) => ReactElement", description: "Provides a caller session or owns one for the subtree." }, { name: "useThemeEditor", signature: "() => { session, snapshot }", description: "Subscribes directly to editor-core immutable state." }, { name: "useThemeEditorAutoPreview", signature: "(runtime?, mode?) => ThemeEditorAutoPreviewState", description: "Coalesces valid revisions per animation frame." }, { name: "re-exported editor-core types", signature: "ThemeEditorOptions, ThemeEditorSession, …", description: "Convenience type/domain re-exports; behavior remains in editor-core." }]} /><CodeBlock language="tsx">{`import { ThemeEditorProvider, useThemeEditorAutoPreview } from "@oriatheme/react-editor";\n\nfunction Bridge({ runtime }: { runtime: OriaThemeRuntime }) {\n  const preview = useThemeEditorAutoPreview(runtime);\n  return <span>{preview.status}</span>;\n}`}</CodeBlock></section><section id="boundary"><h2>{zh ? "可视 UI 位于你的项目" : "Visible UI lives in your project"}</h2><p>{zh ? "此包不导出 Toolbar、Tabs、字段或 CSS。用 CLI 将组件复制到 components/oria-theme-editor，再让路由只组合本地 ThemeEditor、Runtime 和 options。" : "This package exports no Toolbar, Tabs, fields, or CSS. Use the CLI to copy components into components/oria-theme-editor, then let routes compose only the local ThemeEditor, runtime, and options."}</p></section></>,
  };
  if (slug === "vue-editor") return {
    eyebrow: zh ? "API 参考 · Vue 编辑桥接" : "API reference · Vue editor bridge", title: "@oriatheme/vue-editor", description: zh ? "为本地源码 ThemeEditor 提供 Vue provide、Composable 与自动预览协调；不导出可视 UI。" : "Vue provide, Composable, and auto-preview coordination for a local source ThemeEditor; it exports no visible UI.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "Exports" }, { id: "boundary", label: zh ? "可视 UI 边界" : "Visible UI boundary" }],
    body: <><PackageIntro name="vue-editor" install="@oriatheme/editor-core @oriatheme/vue-editor" zh={zh} environment={zh ? "Vue 3.5 的客户端桥接；使用本地 CLI 安装的 ThemeEditor 作为可视根。" : "Vue 3.5 client bridge; use a locally CLI-installed ThemeEditor as the visible root."} /><section id="exports"><h2>Exports</h2><ExportsTable items={[{ name: "provideThemeEditor", signature: "(options | session) => ThemeEditorSession", description: "Provides a caller session or creates an owned session." }, { name: "useThemeEditor", signature: "() => { session, snapshot }", description: "Exposes a readonly shallow editor snapshot ref." }, { name: "useThemeEditorAutoPreview", signature: "(runtime, mode?) => Readonly<ShallowRef<ThemeEditorAutoPreviewState>>", description: "Coalesces valid revisions and preserves the last valid preview." }, { name: "re-exported editor-core types", signature: "ThemeEditorOptions, ThemeEditorSession, …", description: "Convenience type/domain re-exports; behavior remains in editor-core." }]} /><CodeBlock language="ts">{`import { provideThemeEditor, useThemeEditorAutoPreview } from "@oriatheme/vue-editor";\n\nconst session = provideThemeEditor(options);\nconst preview = useThemeEditorAutoPreview(runtime);`}</CodeBlock></section><section id="boundary"><h2>{zh ? "可视 UI 位于你的项目" : "Visible UI lives in your project"}</h2><p>{zh ? "此包不导出完整编辑器或默认 CSS。使用 CLI 安装多文件 Vue 源码组件，并保留 editor-core/runtime 的草稿与原子预览边界。" : "This package exports no complete editor or default CSS. Use the CLI to install multi-file Vue source components and preserve editor-core/runtime draft and atomic-preview boundaries."}</p></section></>,
  };
  return {
    eyebrow: zh ? "API 参考 · 源码组件 CLI" : "API reference · Source-component CLI", title: "@oriatheme/cli", description: zh ? "安全地把可修改的 React/Vue ThemeEditor 源码复制到使用方项目；不是运行时依赖。" : "Safely copy editable React/Vue ThemeEditor source into a consumer project; it is not a runtime dependency.",
    toc: [{ id: "package", label: zh ? "包" : "Package" }, { id: "exports", label: "API" }, { id: "commands", label: zh ? "命令" : "Commands" }, { id: "safety", label: zh ? "安全边界" : "Safety" }],
    body: <><PackageIntro name="cli" install="-D @oriatheme/cli" zh={zh} environment={zh ? "Node 可执行工具。通常用 pnpm dlx、npm exec、yarn dlx 或 bunx 一次性运行，而不是加入浏览器 bundle。" : "A Node executable. Usually run once through pnpm dlx, npm exec, yarn dlx, or bunx instead of adding it to a browser bundle."} /><section id="exports"><h2>Programmatic export</h2><ExportsTable items={[{ name: "runCli", signature: "(args: readonly string[], cwd?: string) => Promise<CliResult>", description: "Runs the CLI programmatically and returns exitCode plus output lines." }]} /></section><section id="commands"><h2>{zh ? "常用命令" : "Common commands"}</h2><PackageManagerTabs label={zh ? "选择 CLI runner" : "Choose a CLI runner"} commands={{ pnpm: "pnpm dlx @oriatheme/cli@latest add theme-editor --framework react --dry-run", npm: "npm exec --yes --package=@oriatheme/cli@latest -- oria add theme-editor --framework react --dry-run", yarn: "yarn dlx @oriatheme/cli@latest add theme-editor --framework react --dry-run", bun: "bunx @oriatheme/cli@latest add theme-editor --framework react --dry-run" }} /><p>{zh ? "add 默认只显示计划并以 code 2 退出；--yes 才写入。--dry-run 不写入且以 code 0 退出。用 --path 指定项目内目录，Vue 将 framework 改为 vue。检查计划后，使用同一种 runner 把 --dry-run 替换为 --yes；diff 使用相同 runner 加 diff theme-editor --framework react。" : "add prints a plan and exits with code 2 by default; only --yes writes. --dry-run performs no writes and exits with code 0. Use --path for an in-project target and vue as the framework for Vue. After review, replace --dry-run with --yes through the same runner; use that runner with diff theme-editor --framework react for differences."}</p></section><section id="safety"><h2>{zh ? "写入前的安全保证" : "Safety before write"}</h2><p>{zh ? "CLI 校验 manifest、框架、版本兼容性、相对路径、文件大小和 SHA-256；拒绝脚本、HTTP、越界和符号链接目标。默认拒绝覆盖，diff 不写入，--overwrite 必须与 --yes 明确确认。CLI 不运行 registry 生命周期脚本，也不上传主题或项目文件。" : "The CLI validates manifests, framework, compatible versions, relative paths, file sizes, and SHA-256. It rejects scripts, HTTP, path escape, and symlink targets. It refuses overwrites by default; diff never writes, and --overwrite requires explicit --yes. The CLI runs no registry lifecycle scripts and uploads no themes or project files."}</p></section></>,
  };
}
