<script setup lang="ts">
import { ref, watch } from "vue";
import type { ResolvedMode, ThemeDefinition } from "@oriatheme/core";
const props = withDefaults(defineProps<{ theme: ThemeDefinition; mode: ResolvedMode; active: boolean; displayName?: string; editable?: boolean }>(), { editable: false });
const emit = defineEmits<{ apply: [origin: HTMLElement]; edit: [origin: HTMLElement]; copy: [origin: HTMLElement]; delete: [origin: HTMLElement]; rename: [name: string] }>();
const renaming = ref(false); const name = ref(props.displayName ?? props.theme.name); watch(() => props.displayName ?? props.theme.name, value => { if (!renaming.value) name.value = value; });
const swatch = (path: string): string => { const value = (props.theme.modes[props.mode] as Readonly<Record<string, unknown>>)[path]; return typeof value === "string" ? value : "transparent"; };
const submit = (): void => { const next = name.value.trim(); if (!next || next.length > 120) return; emit("rename", next); renaming.value = false; };
</script>
<template><article data-oria-editor-theme-item :data-active="active"><div data-oria-editor-theme-preview aria-hidden="true"><span data-oria-editor-palette-icon><i v-for="path in ['color.primary','color.secondary','color.accent','color.selection','color.info']" :key="path" :style="{ backgroundColor: swatch(path) }" /></span></div><div data-oria-editor-theme-body><form v-if="renaming" data-oria-editor-theme-rename @submit.prevent="submit"><label><span class="oria-editor-visually-hidden">Theme name</span><input v-model="name" maxlength="120" autofocus @keydown.escape.prevent="name = displayName ?? theme.name; renaming = false" /></label><button type="submit" data-compact-action :disabled="!name.trim()">Save</button><button type="button" data-compact-action @click="name = displayName ?? theme.name; renaming = false">Cancel</button></form><div v-else data-oria-editor-theme-name><strong>{{ displayName ?? theme.name }}</strong><small>{{ theme.kind === 'custom' ? 'Custom theme' : 'Preset' }}</small></div><div v-if="!renaming" data-oria-editor-theme-actions><button type="button" data-theme-action="apply" :aria-label="active ? `${displayName ?? theme.name} is active` : `Apply ${displayName ?? theme.name}`" :title="active ? 'Active theme' : 'Apply'" :disabled="active" @click="emit('apply',$event.currentTarget as HTMLElement)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12.5 9.2 17 19 7" /></svg><span>{{ active ? 'Active' : 'Apply' }}</span></button><button v-if="editable" type="button" :aria-label="`Rename ${displayName ?? theme.name}`" title="Rename" @click="renaming = true"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h10M9 7v10M5.5 17h7" /><path d="m15 16 4-4 2 2-4 4-3 1 1-3Z" /></svg></button><button v-if="editable" type="button" :aria-label="`Edit ${displayName ?? theme.name}`" title="Edit" @click="emit('edit',$event.currentTarget as HTMLElement)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 20 4.2-1 10.6-10.6-3.2-3.2L5 15.8 4 20Z" /><path d="m13.8 7 3.2 3.2" /></svg></button><button type="button" :aria-label="`Copy and edit ${displayName ?? theme.name}`" title="Copy and edit" @click="emit('copy',$event.currentTarget as HTMLElement)"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2" /><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2" /></svg></button><button v-if="editable" type="button" data-theme-action="delete" :aria-label="`Delete ${displayName ?? theme.name}`" title="Delete" @click="emit('delete',$event.currentTarget as HTMLElement)"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13" /><path d="M10 11v5M14 11v5" /></svg></button></div></div></article></template>
