import { useEffect, useRef, useState } from "react";
import type { CSSProperties, PointerEvent, ReactElement } from "react";
import type { ResolvedMode, ThemeDefinition, TokenPath } from "@oriatheme/core";
export function EditorPreview({ mode, draft, open, onClose }: { readonly mode: ResolvedMode; readonly draft: ThemeDefinition; readonly open: boolean; readonly onClose: () => void }): ReactElement {
  const [expanded, setExpanded] = useState(false); const start = useRef<{ y: number; time: number; lastY: number; lastTime: number } | undefined>(undefined); const [drag, setDrag] = useState(0);
  useEffect(() => { const close = (event: KeyboardEvent): void => { if (open && event.key === "Escape") onClose(); }; globalThis.addEventListener?.("keydown", close); return () => globalThis.removeEventListener?.("keydown", close); }, [onClose, open]);
  const down = (event: PointerEvent<HTMLButtonElement>): void => { event.currentTarget.setPointerCapture(event.pointerId); start.current = { y: event.clientY, time: event.timeStamp, lastY: event.clientY, lastTime: event.timeStamp }; setDrag(0); };
  const move = (event: PointerEvent<HTMLButtonElement>): void => { if (!start.current) return; start.current.lastY = event.clientY; start.current.lastTime = event.timeStamp; setDrag(Math.max(0, event.clientY - start.current.y)); };
  const up = (event: PointerEvent<HTMLButtonElement>): void => { const gesture = start.current; start.current = undefined; if (!gesture) return; const elapsed = Math.max(1, event.timeStamp - gesture.time); const velocity = (event.clientY - gesture.y) / elapsed * 1000; const projected = drag + velocity * .18; setDrag(0); if (projected > 110) onClose(); };
  const tokens = draft.modes[mode]; const token = (name: string) => tokens[name as TokenPath]; const style = { "--preview-bg": String(token("color.background")), "--preview-fg": String(token("color.foreground")), "--preview-surface": String(token("color.surface")), "--preview-primary": String(token("color.primary")), "--preview-radius": String(token("shape.radius.lg")) } as CSSProperties;
  return <aside data-oria-editor-preview data-open={open} data-expanded={expanded} aria-label={`${mode} preview`} style={{ ...style, "--oria-editor-sheet-drag": `${drag}px` } as CSSProperties}><div data-oria-editor-sheet-bar><button type="button" aria-label="Drag preview sheet" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}><i /></button><button type="button" onClick={() => setExpanded(value => !value)}>{expanded ? "Compact" : "Expand"}</button><button type="button" aria-label="Close preview" onClick={onClose}>×</button></div><div><small>Live preview · {mode}</small><h2>Design that feels at home.</h2><p>Every valid change arrives atomically while the editor stays steady.</p><button type="button">Primary action</button><span>Secondary detail</span></div></aside>;
}
