import { defineTokenContract, token } from "./contract.js";
import type { ThemeDefinition, ThemeTokenInput, TokenDefinition, TokenPath } from "./types.js";

const definitions: Record<string, TokenDefinition> = {};
const add = (path: string, definition: TokenDefinition): void => { definitions[path] = definition; };
const required = (type: TokenDefinition["type"], description: string, options: Omit<TokenDefinition, "type" | "required" | "description"> = {}): void => { add(description.split("|")[0]!, token(type, { required: true, description: description.split("|")[1] ?? description, ...options })); };
const optional = (type: TokenDefinition["type"], path: string, description: string): void => add(path, token(type, { required: false, description }));

for (const path of ["background", "foreground", "surface", "surfaceForeground", "surfaceRaised", "surfaceRaisedForeground", "overlay", "overlayForeground", "primary", "primaryForeground", "primaryHover", "primaryActive", "secondary", "secondaryForeground", "secondaryHover", "secondaryActive", "muted", "mutedForeground", "accent", "accentForeground", "destructive", "destructiveForeground", "success", "successForeground", "warning", "warningForeground", "info", "infoForeground", "border", "borderStrong", "input", "ring", "selection", "selectionForeground", "scrim", ...Array.from({ length: 8 }, (_, index) => `chart${index + 1}`)]) required("color", `color.${path}|Semantic color token.`);
for (const path of ["sans", "serif", "mono", "display"]) required("fontFamily", `typography.font.${path}|Font-family list.`);
for (const path of ["thin", "extraLight", "light", "normal", "medium", "semibold", "bold", "extraBold", "black"]) required("fontWeight", `typography.weight.${path}|Font weight.`);
for (const path of ["xs", "sm", "md", "lg", "xl", "2xl", "3xl", "4xl", "5xl", "6xl", "7xl", "8xl", "9xl"]) required("dimension", `typography.size.${path}|Type size.`);
for (const path of ["tight", "snug", "normal", "relaxed", "loose"]) required("number", `typography.lineHeight.${path}|Unitless line height.`);
for (const path of ["tighter", "tight", "normal", "wide", "wider", "widest"]) required("dimension", `typography.letterSpacing.${path}|Letter spacing.`);
for (const path of ["none", "xs", "sm", "md", "lg", "xl", "2xl", "3xl", "4xl", "full"]) required("dimension", `shape.radius.${path}|Corner radius.`);
for (const path of ["hairline", "default", "strong"]) required("dimension", `shape.borderWidth.${path}|Border width.`);
for (const path of ["focusRingWidth", "focusRingOffset"]) required("dimension", `shape.${path}|Focus ring dimension.`);
required("dimension", "spacing.unit|Base spacing unit.");
required("number", "spacing.density|Spacing density.", { minimum: 0.75, maximum: 1.25 });
for (const path of ["1", "2", "3", "4", "5", "6", "8", "10", "12", "16"]) required("dimension", `spacing.${path}|Spacing scale.`);
for (const path of ["sm", "md", "lg"]) { required("dimension", `control.height.${path}|Control height.`); required("dimension", `control.paddingInline.${path}|Control inline padding.`); }
for (const path of ["none", "2xs", "xs", "sm", "md", "lg", "xl", "2xl", "inner", "highlight"]) required("shadow", `elevation.shadow.${path}|Structured elevation shadow.`);
for (const path of ["disabled", "muted", "overlay"]) required("number", `effect.opacity.${path}|Opacity.`, { minimum: 0, maximum: 1 });
for (const path of ["xs", "sm", "md", "lg", "xl", "2xl", "3xl"]) required("dimension", `effect.blur.${path}|Blur radius.`);
for (const path of ["xs", "sm", "md", "lg", "xl", "2xl", "3xl"]) required("dimension", `effect.backdropBlur.${path}|Backdrop blur radius.`);
required("number", "effect.backdropSaturation|Backdrop saturation.", { minimum: 0, maximum: 3 });
for (const path of ["background", "surface", "accent"]) optional("gradient", `gradient.${path}`, "Optional structured gradient.");
optional("pattern", "pattern.background", "Optional ordered, structured background-pattern layers.");
optional("pattern", "pattern.surface", "Optional ordered, structured surface-pattern layers.");
for (const path of ["instant", "fast", "normal", "slow"]) required("duration", `motion.duration.${path}|Motion duration.`);
for (const path of ["standard", "entrance", "exit", "emphasized"]) required("cubicBezier", `motion.easing.${path}|Motion easing.`);

/** Standard v1 design-language contract. Stable base colors live in @oriatheme/colors. */
/** Legacy v1 contract, retained for explicit migration of previously published themes. */
export const oriaStandardContractV1 = defineTokenContract({ name: "oria-standard", version: 1, tokens: definitions });

const shared: Record<string, ThemeTokenInput> = {
  "typography.font.sans": ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Inter", "sans-serif"], "typography.font.serif": ["Iowan Old Style", "Palatino Linotype", "Georgia", "serif"], "typography.font.mono": ["SFMono-Regular", "Cascadia Code", "Consolas", "monospace"], "typography.font.display": ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "Inter", "sans-serif"],
  "typography.weight.thin": "100", "typography.weight.extraLight": "200", "typography.weight.light": "300", "typography.weight.normal": "400", "typography.weight.medium": "500", "typography.weight.semibold": "600", "typography.weight.bold": "700", "typography.weight.extraBold": "800", "typography.weight.black": "900",
  "typography.size.xs": "0.75rem", "typography.size.sm": "0.875rem", "typography.size.md": "1rem", "typography.size.lg": "1.125rem", "typography.size.xl": "1.25rem", "typography.size.2xl": "1.5rem", "typography.size.3xl": "1.875rem", "typography.size.4xl": "2.25rem", "typography.size.5xl": "3rem", "typography.size.6xl": "3.75rem", "typography.size.7xl": "4.5rem", "typography.size.8xl": "6rem", "typography.size.9xl": "8rem",
  "typography.lineHeight.tight": 1.2, "typography.lineHeight.snug": 1.35, "typography.lineHeight.normal": 1.5, "typography.lineHeight.relaxed": 1.7, "typography.lineHeight.loose": 2,
  "typography.letterSpacing.tighter": "-0.05em", "typography.letterSpacing.tight": "-0.02em", "typography.letterSpacing.normal": "0em", "typography.letterSpacing.wide": "0.04em", "typography.letterSpacing.wider": "0.06em", "typography.letterSpacing.widest": "0.1em",
  "shape.radius.none": "0", "shape.radius.xs": "0.375rem", "shape.radius.sm": "0.625rem", "shape.radius.md": "0.875rem", "shape.radius.lg": "1.125rem", "shape.radius.xl": "1.5rem", "shape.radius.2xl": "2rem", "shape.radius.3xl": "3rem", "shape.radius.4xl": "4rem", "shape.radius.full": "9999px",
  "shape.borderWidth.hairline": "1px", "shape.borderWidth.default": "1px", "shape.borderWidth.strong": "2px", "shape.focusRingWidth": "2px", "shape.focusRingOffset": "3px",
  "spacing.unit": "0.25rem", "spacing.density": 1.04, "spacing.1": "0.25rem", "spacing.2": "0.5rem", "spacing.3": "0.75rem", "spacing.4": "1rem", "spacing.5": "1.25rem", "spacing.6": "1.5rem", "spacing.8": "2rem", "spacing.10": "2.5rem", "spacing.12": "3rem", "spacing.16": "4rem",
  "control.height.sm": "2.25rem", "control.height.md": "2.75rem", "control.height.lg": "3.25rem", "control.paddingInline.sm": "0.75rem", "control.paddingInline.md": "1rem", "control.paddingInline.lg": "1.25rem",
  "elevation.shadow.none": [], "elevation.shadow.2xs": [{ x: "0", y: "1px", blur: "0", spread: "0", color: "#0000000d" }], "elevation.shadow.xs": [{ x: "0", y: "1px", blur: "2px", spread: "0", color: "#00000014" }], "elevation.shadow.sm": [{ x: "0", y: "1px", blur: "3px", spread: "0", color: "#0000001f" }], "elevation.shadow.md": [{ x: "0", y: "4px", blur: "6px", spread: "-1px", color: "#0000001f" }], "elevation.shadow.lg": [{ x: "0", y: "10px", blur: "15px", spread: "-3px", color: "#0000001f" }], "elevation.shadow.xl": [{ x: "0", y: "20px", blur: "25px", spread: "-5px", color: "#0000001f" }], "elevation.shadow.2xl": [{ x: "0", y: "25px", blur: "50px", spread: "-12px", color: "#00000040" }], "elevation.shadow.inner": [{ x: "0", y: "2px", blur: "4px", spread: "0", color: "#0000000f", inset: true }], "elevation.shadow.highlight": [{ x: "0", y: "1px", blur: "0", spread: "0", color: "#ffffff80", inset: true }],
  "effect.opacity.disabled": 0.5, "effect.opacity.muted": 0.72, "effect.opacity.overlay": 0.82, "effect.blur.xs": "2px", "effect.blur.sm": "4px", "effect.blur.md": "8px", "effect.blur.lg": "16px", "effect.blur.xl": "24px", "effect.blur.2xl": "40px", "effect.blur.3xl": "64px", "effect.backdropBlur.xs": "4px", "effect.backdropBlur.sm": "8px", "effect.backdropBlur.md": "14px", "effect.backdropBlur.lg": "20px", "effect.backdropBlur.xl": "28px", "effect.backdropBlur.2xl": "40px", "effect.backdropBlur.3xl": "64px", "effect.backdropSaturation": 1.18,
  "motion.duration.instant": "0", "motion.duration.fast": "140ms", "motion.duration.normal": "220ms", "motion.duration.slow": "340ms", "motion.easing.standard": [0.2, 0, 0, 1], "motion.easing.entrance": [0, 0, 0.2, 1], "motion.easing.exit": [0.4, 0, 1, 1], "motion.easing.emphasized": [0.16, 1, 0.3, 1]
};
const colors = (dark: boolean): Record<string, ThemeTokenInput> => ({
  "color.background": dark ? "#101418" : "#f1f3f4", "color.foreground": dark ? "#eef3f6" : "#1d2023", "color.surface": dark ? "#192126" : "#f5f7f8", "color.surfaceForeground": dark ? "#eef3f6" : "#1d2023", "color.surfaceRaised": dark ? "#222c32" : "#fbfcfd", "color.surfaceRaisedForeground": dark ? "#f5f8fa" : "#1d2023", "color.overlay": dark ? "#1d272d" : "#ffffff", "color.overlayForeground": dark ? "#f5f8fa" : "#1d2023",
  "color.primary": dark ? "#4cc8f5" : "#35bff0", "color.primaryForeground": dark ? "#06222c" : "#07232d", "color.primaryHover": dark ? "#72d5f8" : "#22afe4", "color.primaryActive": dark ? "#2db8ea" : "#0d94c9", "color.secondary": dark ? "#283239" : "#f9fafb", "color.secondaryForeground": dark ? "#f5f8fa" : "#22272b", "color.secondaryHover": dark ? "#333f47" : "#eff2f4", "color.secondaryActive": dark ? "#404d55" : "#e3e8eb", "color.muted": dark ? "#20292f" : "#e9edef", "color.mutedForeground": dark ? "#b6c0c6" : "#656d73", "color.accent": dark ? "#123f50" : "#d4f3fd", "color.accentForeground": dark ? "#ccf3ff" : "#0c5069",
  "color.destructive": dark ? "#f46767" : "#d53740", "color.destructiveForeground": dark ? "#101418" : "#ffffff", "color.success": dark ? "#56b17c" : "#1f9058", "color.successForeground": "#101418", "color.warning": dark ? "#fba171" : "#c15701", "color.warningForeground": dark ? "#101418" : "#ffffff", "color.info": dark ? "#52a4db" : "#1982bd", "color.infoForeground": dark ? "#101418" : "#000000",
  "color.border": dark ? "#ffffff1c" : "#ffffffa8", "color.borderStrong": dark ? "#ffffff4d" : "#cbd2d7", "color.input": dark ? "#182126" : "#f7f9fa", "color.ring": dark ? "#4cc8f5" : "#35bff0", "color.selection": dark ? "#155b78" : "#bdeefe", "color.selectionForeground": dark ? "#f2fbff" : "#10394a", "color.scrim": dark ? "#000000a3" : "#17202766",
  "color.chart1": dark ? "#4cc8f5" : "#35bff0", "color.chart2": dark ? "#52a4db" : "#1982bd", "color.chart3": dark ? "#4caea6" : "#1c8c85", "color.chart4": dark ? "#56b17c" : "#1f9058", "color.chart5": dark ? "#5f99fe" : "#3675e2", "color.chart6": dark ? "#8390f8" : "#626bdc", "color.chart7": dark ? "#f46767" : "#d53740", "color.chart8": dark ? "#fba171" : "#c15701",
  "elevation.shadow.2xs": dark ? [{ x: "0", y: "1px", blur: "2px", spread: "-1px", color: "#00000052" }] : [{ x: "0", y: "1px", blur: "2px", spread: "-1px", color: "#1b40520d" }],
  "elevation.shadow.xs": dark ? [{ x: "0", y: "2px", blur: "6px", spread: "-3px", color: "#00000066" }, { x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffff24", inset: true }] : [{ x: "0", y: "2px", blur: "6px", spread: "-3px", color: "#1b405214" }, { x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffffd9", inset: true }],
  "elevation.shadow.sm": dark ? [{ x: "0", y: "6px", blur: "16px", spread: "-8px", color: "#00000080" }, { x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffff29", inset: true }] : [{ x: "0", y: "6px", blur: "16px", spread: "-8px", color: "#1b40521f" }, { x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffffe6", inset: true }],
  "elevation.shadow.md": dark ? [{ x: "0", y: "14px", blur: "34px", spread: "-18px", color: "#00000099" }] : [{ x: "0", y: "14px", blur: "34px", spread: "-18px", color: "#1b40522e" }],
  "elevation.shadow.lg": dark ? [{ x: "0", y: "20px", blur: "46px", spread: "-22px", color: "#000000a3" }] : [{ x: "0", y: "20px", blur: "46px", spread: "-22px", color: "#1b405238" }],
  "elevation.shadow.xl": dark ? [{ x: "0", y: "26px", blur: "60px", spread: "-26px", color: "#000000ad" }] : [{ x: "0", y: "26px", blur: "60px", spread: "-26px", color: "#1b405242" }],
  "elevation.shadow.2xl": dark ? [{ x: "0", y: "34px", blur: "80px", spread: "-32px", color: "#000000b8" }] : [{ x: "0", y: "34px", blur: "80px", spread: "-32px", color: "#1b40524d" }],
  "elevation.shadow.inner": dark ? [{ x: "0", y: "2px", blur: "5px", spread: "0", color: "#00000066", inset: true }, { x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffff1f", inset: true }] : [{ x: "0", y: "2px", blur: "5px", spread: "0", color: "#1b40521f", inset: true }, { x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffff", inset: true }],
  "elevation.shadow.highlight": dark ? [{ x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffff38", inset: true }, { x: "-1px", y: "0", blur: "0", spread: "0", color: "#ffffff24", inset: true }, { x: "0", y: "1px", blur: "0", spread: "0", color: "#0000004d", inset: true }, { x: "1px", y: "0", blur: "0", spread: "0", color: "#0000003d", inset: true }] : [{ x: "0", y: "-1px", blur: "0", spread: "0", color: "#ffffff", inset: true }, { x: "-1px", y: "0", blur: "0", spread: "0", color: "#ffffffe6", inset: true }, { x: "0", y: "1px", blur: "0", spread: "0", color: "#b9c6cc4d", inset: true }, { x: "1px", y: "0", blur: "0", spread: "0", color: "#b9c6cc3d", inset: true }]
});
const tokensFor = (dark: boolean): Readonly<Record<TokenPath, ThemeTokenInput>> => Object.freeze({ ...shared, ...colors(dark) } as Record<TokenPath, ThemeTokenInput>);
/** Complete built-in preset with AA body text combinations in both modes. */
/** Legacy v1 default theme; the canonical visual baseline for the v2 default. */
export const oriaDefaultThemeV1: ThemeDefinition = Object.freeze({ schemaVersion: 1, contract: { name: "oria-standard", version: 1 }, id: "oria-default", name: "Default", kind: "preset", modes: Object.freeze({ light: tokensFor(false), dark: tokensFor(true) }) });
