<script setup lang="ts">
import { ref } from "vue";
import type { ThemeEditorSession } from "@oriatheme/editor-core";
import { exportThemeCode } from "../export-theme-code";
import { useDetailsDismiss } from "../composables/useDetailsDismiss";
const props = defineProps<{ session: ThemeEditorSession; disabled: boolean }>();
const menu = ref<HTMLDetailsElement>(); const copied = ref<"typescript" | "json">(); useDetailsDismiss(menu);
const copy = async (format: "typescript" | "json"): Promise<void> => { const draft = props.session.getSnapshot().draft; await globalThis.navigator.clipboard.writeText(format === "typescript" ? exportThemeCode(draft) : props.session.exportJson()); copied.value = format; globalThis.setTimeout(() => { copied.value = undefined; }, 1500); };
const download = (format: "typescript" | "json"): void => { const draft = props.session.getSnapshot().draft; const content = format === "typescript" ? exportThemeCode(draft) : props.session.exportJson(); const type = format === "typescript" ? "text/typescript;charset=utf-8" : "application/json"; const url = URL.createObjectURL(new Blob([content], { type })); const link = globalThis.document.createElement("a"); link.href = url; link.download = `${draft.id}.oria-theme.${format === "typescript" ? "ts" : "json"}`; link.click(); URL.revokeObjectURL(url); };
</script>
<template><details ref="menu" data-oria-editor-menu><summary :aria-disabled="disabled" :aria-label="copied ? `Theme ${copied === 'typescript' ? 'TypeScript' : 'JSON'} copied` : 'Export theme'" :title="copied ? 'Copied' : 'Export'"><svg data-oria-editor-action-icon viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m-4-4 4 4 4-4M5 19h14" /></svg><span data-oria-editor-action-label>{{ copied ? "Copied" : "Export" }}</span></summary><div role="menu"><button role="menuitem" type="button" :disabled="disabled" @click="copy('typescript')">Copy TypeScript</button><button role="menuitem" type="button" :disabled="disabled" @click="download('typescript')">Download TypeScript</button><button role="menuitem" type="button" :disabled="disabled" @click="copy('json')">Copy JSON</button><button role="menuitem" type="button" :disabled="disabled" @click="download('json')">Download JSON</button></div></details></template>
