<script setup lang="ts">
import { nextTick, onBeforeUnmount, ref, watch } from "vue";
import type { ThemeEditorSession } from "@oriatheme/editor-core";
const props = defineProps<{ session: ThemeEditorSession }>();
const dialog = ref<HTMLDialogElement>(); const fileInput = ref<HTMLInputElement>(); const text = ref(""); const fileName = ref(""); const message = ref(""); const open = ref(false);
let previousRootOverflow = ""; let previousBodyOverflow = "";
const unlock = (): void => { globalThis.document.documentElement.style.overflow = previousRootOverflow; globalThis.document.body.style.overflow = previousBodyOverflow; };
watch(open, async active => { if (!active) { unlock(); return; } previousRootOverflow = globalThis.document.documentElement.style.overflow; previousBodyOverflow = globalThis.document.body.style.overflow; globalThis.document.documentElement.style.overflow = "hidden"; globalThis.document.body.style.overflow = "hidden"; await nextTick(); dialog.value?.showModal(); fileInput.value?.focus({ preventScroll: true }); });
onBeforeUnmount(unlock);
const load = async (event: Event): Promise<void> => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; fileName.value = file.name; message.value = ""; try { text.value = await file.text(); } catch { message.value = "The selected file could not be read."; } };
const commit = (): void => { const result = props.session.replaceFromJson(text.value); if (result.ok) { message.value = "Imported into the unsaved draft."; dialog.value?.close(); } else message.value = result.issues[0]?.message ?? "Theme JSON is invalid."; };
</script>
<template><button type="button" aria-label="Import theme JSON" title="Import" @click="open = true"><svg data-oria-editor-action-icon viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m-4-4 4 4 4-4M5 19h14" /></svg><span data-oria-editor-action-label>Import</span></button><dialog ref="dialog" data-oria-editor-dialog data-oria-editor-import @cancel="message = ''" @close="open = false"><form method="dialog"><header><div><small>Atomic import</small><h2>Import theme JSON</h2><p>Choose an Oria theme file or paste its JSON below.</p></div><button data-oria-editor-dialog-close aria-label="Close import" value="cancel"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18" /></svg></button></header><section data-oria-editor-import-file aria-labelledby="oria-import-file-title"><div data-oria-editor-import-file-copy><span data-oria-editor-import-file-icon aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 5.5A1.5 1.5 0 0 1 5.5 4h4l2 2H18.5A1.5 1.5 0 0 1 20 7.5v10a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 17.5Z" /><path d="M12 9v6m-2-2 2 2 2-2" /></svg></span><div><h3 id="oria-import-file-title">Theme file</h3><p>.oria-theme.json or .json</p></div></div><label data-oria-editor-file-picker><input ref="fileInput" class="oria-editor-visually-hidden" type="file" accept=".oria-theme.json,.json,application/json" @change="load" /><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 16V4m-4 4 4-4 4 4M5 20h14" /></svg><span>Choose file</span></label><p data-oria-editor-file-name :data-selected="Boolean(fileName)" aria-live="polite">{{ fileName || "No file selected" }}</p></section><div data-oria-editor-import-divider><span>or paste JSON</span></div><label data-oria-editor-import-paste><span>Theme JSON</span><textarea v-model="text" rows="8" spellcheck="false" placeholder="Paste a complete Oria theme definition…" @input="fileName = ''; message = ''" /></label><p v-if="message" data-oria-editor-error role="alert">{{ message }}</p><footer><button value="cancel">Cancel</button><button data-oria-editor-primary type="button" :disabled="!text.trim()" @click="commit">Import to draft</button></footer></form></dialog></template>
